name: cardiac_data
channels:
  - defaults
dependencies:
  - python=3.7.9
  - numpy
  - pandas
  - matplotlib
  - plotly
  - wxpython
  - pivottablejs
  - pip
  - pip:
    - pydicom==2.1.1
    - dicomsorter
    - pypng

